### ISSUE TITLE
A-소인수분해

### ISSUE THREAD

**Issue by phillyai** [Big-BlueBerry/MathIsh#10]
- 문제 이름: A-소인수분해
- 문제 출처: 4607

---

`3k+1`꼴의 모든 자연수들을 모은 집합을 `A`라 하자. `n∈A`일 때, `n`이 1과 자
기 자신이외에는 `A`에 속하는 약수를 갖지 않으면 `n`을 `A-소수`라고 한다. 그
리고 `A` 의 원소들을 `A-소수`들의 곱으로 나타내는 것을 `A-소인수분해`라고 
한다. 곱하는 순서를 무시할 때, A-소인수분해는 보통의 소인수분해처럼 항상 
유일한가?

**Comment by bigblueberry** [comment]
'그리고 의 원소들을 A-소수들의 곱으로 나타내는 것을'
중간에 글자빠짐

**Comment by phillyai** [comment]
너가 문서 보고 추가해주면 안됨? 두번째 문젠데

**Comment by phillyai** [comment]
반례
100=10x10=4x25
