### ISSUE TITLE
abctuv

### ISSUE THREAD

**Issue by phillyai** [Big-BlueBerry/MathIsh#11]
- 문제 이름: abctuv
- 문제 출처: 4608

---

세  정수 `a, b, c`가 `ab=c^2`을 만족하면, 
적당한 정수 `t, u, v`에 대해 `a=tu^2, b=tv^2`이 됨을 보여라.

**Comment by phillyai** [comment]
t가 a b의 최대공약수이면 성립

**Comment by bigblueberry** [comment]
그러네 진짜 개쉽네

**Comment by phillyai** [comment]
ㅋㅋㅋㅋ 이거 원래 풀이보니까 소인수분해한다음 뭔가 복잡하게 하네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
