### ISSUE TITLE
Prime Numbers

### ISSUE THREAD

**Issue by bigblueberry** [Big-BlueBerry/MathIsh#2]
- 문제 이름: Prime Numbers
- 문제 출처:  https://cafe.naver.com/cmcmathematics/363

---

> 모든 소수를 작은 것부터 차례대로 p_1, p_2, .. 라 할 때, n보다 작고 n과 서로소인 자연수 d 가 모두 소수인 n의 최대값은 30임을 이용하여 다음을 보여라.
p_1 * p_2 * ... p_k > (p_(k+1))^2

**Comment by phillyai** [comment]
조건 추가: k>=4

**Comment by bigblueberry** [comment]
solved
