### ISSUE TITLE
C^ Inf 함수를 찾아라

### ISSUE THREAD

**Issue by bigblueberry** [Big-BlueBerry/MathIsh#22]
- 문제 이름: C ^ Inf 함수를 찾아라
- 문제 출처: SNU Press 해석개론

---

> C^n 함수란 n회 미분이 가능하고 n계 도함수가 연속인 함수를 말한다. 다음 조건을 만족하는 C^Infinity 함수 g(x) 의 예를 하나 들어라.
g(x)= 1 if x>1, g(x) = 0 if x< 0

**Comment by phillyai** [comment]
나도 도전해봐야지
일단은 포기

**Comment by bigblueberry** [comment]
일단 풀었는데 열어놓고있는다
