### ISSUE TITLE
1993번째 점

### ISSUE THREAD

**Issue by phillyai** [Big-BlueBerry/MathIsh#4]
- 문제 이름: 1993번째 점
- 문제 출처: https://cafe.naver.com/cmcmathematics/12140

---
한 원 위에 2000개의 점이 있는데, 다음과 같이 1, 2, 3, .., 1993의 수를 각 점에 부여한다. 먼저 아무 점에나 1을 부여하고, 거기서 시계방향으로 두번째 점에 2를 부여한다. 거기서 다시 시계방향으로 3번째 점에 3을 부여하고, 이런 식으로 계속한다. 어떤 점들에는 둘 이상의 수가 중복되어 부여되었을 수 있다. 1993이 부여된 점에 함께 부여된 수들 중에서 가장 작은 것은 무엇인가?

**Comment by bigblueberry** [comment]
어떻게됨

**Comment by phillyai** [comment]
![default](https://user-images.githubusercontent.com/16171816/48325379-a136fe80-e678-11e8-9d06-7c70d7ce47f2.png)

이런식으로 접근해서 결국 방정식이 나왔는데 그게 일일히 해를 찾기에는 수가 너무 커서 일단 패스하고이ㅣㅅ음 ㅠ

**Comment by phillyai** [comment]
모든 점을 p1 에서 p2000 까지 잡았을때 1993이 있는 점은 p1021이고 그래서 그 점을 지나는 수 n은 2n=-1 + sqrt(1600x + 8169) 가 성립함. 그러한 수 n을 찾으면 되는데 n=1993 이면 x=9930 임. 범위가 너무 넓어서 이렇게 하나 하나 구하는 방법은 아닌 것 같음

**Comment by bigblueberry** [comment]
이렇게 해보는건 어떰
그니까 x(x+1)/2 === 1021 mod 2000 인 x들을 모두 찾아야 하는건데
그런 두 개의 수 n, m이 있다 가정하면 n(n+1)/2 - m(m+1)/2 ===0 mod 2000 이고 결국 n(n+1) - m(m+1) 은 4000의 배수 -> n^2 -m^2 + n-m = (n-m)(n+m+1) 은 4000의 배수. 이제 하나의 해 n =1993 을 대입하면 (1993 -m)(1993+m+1)은 4000의 배수여야 하고 곱해진 두 개 중 적어도 하나는 10의 배수이고 두 개를 곱하면 1000의 배수여야 하므로 (m의 일의자릿수를 생각하면) m의 값에 아주 상당한 제약이 있을거같음.

**Comment by bigblueberry** [comment]
아 아니네 ㅅㅂ 적어도 하나가 10의 배수가 아닐수도 있구나 ㅇㅇ
어쨌든 이런식으로 하는건 어떪

**Comment by phillyai** [comment]
첨엔 그런식으로 접근을 해봤는데 그게 그래도 역시 노가다더라고 필터링을 최대한 많이 붙이는거가 좋은 방향이 아닐 수 있어

**Comment by bigblueberry** [comment]
아 근데 내가 실수했지만 그 실수로부터 나온게 상당히 재밌는데 저러면 한쪽만 1000의 배수고 나머지는 아니거나, 두 쪽 다 10의 배수가 아님(한쪽은 2^5, 한쪽은 5^3의 배수). 왜냐면 둘다 짝수이면 안되니까..
그리고 모든 m을 찾는게 아니고 최소의 m이면 더 쉽지 않냐? 저 조건만 통과하면 되는거잖아

**Comment by phillyai** [comment]
아 아니네 이해를 못했엇다 모듈러 식 빼서 0 만드는건 상상도 못함 ㅋ... 구불빡이엇다 그렇게 접근하면 훨씬 쉽겠다 밥먹고 해봄

**Comment by phillyai** [comment]
근데 그래도 범위가 넓긴 매한가지인듯... 홀/짝 짝/홀 인 경우 두가지 각각 `m === 22 (mod 32)` 와 `m === 10 (mod 32)` 거든 n = 1993 에 비하면 m의 가지수가 너무 클거같엉

**Comment by phillyai** [comment]
2번 조건으로 5의 위치가 갈려버리네.. 그렇게 되서 16가지정도만 구해줘서 가장 작은 m 값으로 답을 찾으면 된다. ..

**Comment by phillyai** [comment]
풀었음 우림짱
