### ISSUE TITLE
세제곱수

### ISSUE THREAD

**Issue by phillyai** [Big-BlueBerry/MathIsh#5]
- 문제 이름: 
- 문제 출처: 문풀대 4606

---

a, b, c가 양의 정수이고 ab, bc, ca가 모두 세제곱수이면 a, b, c도 모두 세제
곱수임을 증명하여라.

**Comment by phillyai** [comment]
근데 이거 뭔가 거시기하지 않음? `a^2b^2c^2`가 세제곱수일때 `abc` 가 세제곱수란거만 보이면 a b c 전부 세제곱수인거 나눠서 보이면 되잖아 너무 섹시하지 않아 @bigblueberry

**Comment by bigblueberry** [comment]
앗 이거 니가 논리전개하면서 걍 생략한줄알고 그러려니 했는데 
a, b -> (0, 0)  mod 3 이어야 하는 이유는 정확히 그 소인수 p를 c에서도 생각했을때
a + b === 0 mod3
b + c === 0 mod3
c + a === 0 mod3
을 전부 만족하려면 a, b, c = (0, 0, 0) mod 3 이 유일한 해라서 그런거아님?
그냥 a^2b^2c^2 로 말하는거면 (a, b, c) = (2, 1, 0) 같은거도 가능하지만 이러면 (a, c) = (2, 0)이라 fail.
니가 한얘기가 이거랑 일치한다면 굳이 a^2b^2c^2는 언급할 필요가 없음

**Comment by bigblueberry** [comment]
설명해보자면 a^2b^2c^2 가 세제곱수이면 각 소인수의 지수는 3과 2의 공배수.
abc는 각 소인수들의 지수가 1/2배 되어 있는데, 2와 3은 서로소라 영향을 주지 않으므로 abc의 소인수의 지수는 3의 배수.

**Comment by phillyai** [comment]
와우 바로 이해가쓰...

**Comment by phillyai** [comment]
그러면 설명 좀 다듬어야겠다

**Comment by phillyai** [comment]
나이쓰
