### ISSUE TITLE
정렬

### ISSUE THREAD

**Issue by bigblueberry** [Big-BlueBerry/MathIsh#8]
- 문제 이름: 정렬
- 문제 출처: 자작

---

> 1,2,...n의 임의의 재배열이 있을 때, 이 재배열을 어느 방법으로 정렬하여 1,2,...n으로 만들어도 교환 횟수의 홀짝성은 항상 같음을 보여라. (단, 정렬을 할 때 임의의 두 원소를 교환하는 것만 허용된다.)

**Comment by phillyai** [comment]
정렬을 할때 스왚만이 가능하다는 조건을 빼먹은듯
